include $(GNUSTEP_MAKEFILES)/common.make

USE_OBJC_EXCEPTIONS = yes
ADDITIONAL_OBJCFLAGS = -fgnu-runtime -fconstant-string-class=NSConstantString

TOOL_NAME = scgen
scgen_OBJC_FILES = \
sc_gen.m \


include $(GNUSTEP_MAKEFILES)/tool.make

